---

docker_consul_image: 'progrium/consul:latest'

docker_consul_tls_dir: '/etc/consul/ssl/'
docker_consul_tls_ca_cert_file: '/etc/consul/ssl/ca.cert'
docker_consul_tls_ca_key_file: ''
docker_consul_tls_server_cert_file: '/etc/consul/ssl/consul.cert'
docker_consul_tls_server_key_file: '/etc/consul/ssl/consul.key'